R CMD BATCH --no-restore --no-save code/01_compute_econphd.R 
R CMD BATCH --no-restore --no-save code/02_convert_tables.R 
R CMD BATCH --no-restore --no-save code/03_tabulate_access_aea.R 
R CMD BATCH --no-restore --no-save code/04_tabulate_access_categories.R 
R CMD BATCH --no-restore --no-save code/11_get_crossref.R 
R CMD BATCH --no-restore --no-save code/13_analyse_authors.R 
R CMD BATCH --no-restore --no-save code/20_geocode_stata_step1.R 
R CMD BATCH --no-restore --no-save code/21_geocode_stata_step2.R 
R CMD BATCH --no-restore --no-save code/22_generate_download_map.R 
R CMD BATCH --no-restore --no-save code/25_download_R_logs.R 
R CMD BATCH --no-restore --no-save code/26_aggregate_data.R 
R CMD BATCH --no-restore --no-save code/27_map_R_by_country.R 
R CMD BATCH --no-restore --no-save code/28_stata_map_by_country.R 
R CMD BATCH --no-restore --no-save code/29_compare_stata_r_by_region.R 
R CMD BATCH --no-restore --no-save code/libraries.R 
